language: node_js
node_js:
  - '0.11'
install:
  - npm install
  - sudo apt-get install python-pygments
script:
  - node_modules/.bin/jshint lib
  - bin/test.sh
after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - npm run deploy-doc
services:
  - mongodb
env:
  global:
    secure: Fk186bbxQmuQFaWDwb0FM0NIAQ5itsRkNZHS6D+ihckAs0Mxuwv4ZABLUrl6qky9IwXBc0rt9rEnrNS7uJinoQu/gwtfF7tbxKLw8XkwJSi+zJOOH+flLxmCPMOBZUaShI62wwJTchDYETPknVTO6w7CVl20ODmpz4fxgSmgsU4=
