FORMAT: 1A
HOST: http://localhost

# KaThinka
Is testing api for **KaThinka** project

# Group Root

## Retrieve Entry Point [/]
### Check if api is connected to db and running [GET]
+ Response 200 (application/json; charset=utf-8)

    + Schema

            {
                "$schema": "http://json-schema.org/draft-03/schema#",
                "type": "object",
                "required": true,
                "properties": {
                    "status": {
                        "type": "string",
                        "required": true
                    },
                    "version": {
                        "type": "string",
                        "required": true
                    }
                }
            }


    + Body

            {
                "status": "ok",
                "version": "1"
            }

# Group Todos
Todos related resources of the **Todos API**

## Todos Collection [/todos]

### Create a Todo [POST]
+ Request (application/json; charset=utf-8)

        {
            "label": "bread",
            "is_done": false
        }

+ Response 201 (application/json; charset=utf-8)

    + Schema

            {
                "$schema": "http://json-schema.org/draft-03/schema#",
                "type": "object",
                "required": true,
                "properties": {
                    "_id": {
                        "type": "string",
                        "required": true
                    },
                    "label": {
                        "type": "string",
                        "required": true
                    },
                    "is_done": {
                        "type": "boolean",
                        "required": true
                    }
                }
            }


    + Body

            {
                "_id": "53ecc8132e6e0d837bc5af70",
                "label": "bread",
                "is_done": false
            }

### List all Todos [GET]
+ Response 200 (application/json; charset=utf-8)

    + Schema

            {
                "$schema": "http://json-schema.org/draft-03/schema#",
                "type": "array",
                "required": true,
                "items": [{
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string",
                        "required": true
                      },
                      "label": {
                        "type": "string",
                        "required": true
                      },
                      "is_done": {
                        "type": "boolean",
                        "required": true
                      }
                    }
                }]
            }


    + Body

            [{
                "_id": "53ecc8132e6e0d837bc5af70",
                "label": "bread",
                "is_done": false
            }]

## Todo [/todos/{label}]
A single Todo object with all its details

+ Parameters
    + label (required, string, `bread`) ... user label `label` of the Todo to perform action with.


### Retrieve the Todo [GET]
+ Response 200 (application/json; charset=utf-8)

    + Schema

            {
                "$schema": "http://json-schema.org/draft-03/schema#",
                "type": "object",
                "required": true,
                "properties": {
                    "_id": {
                        "type": "string",
                        "required": true
                    },
                    "label": {
                        "type": "string",
                        "required": true
                    },
                    "is_done": {
                        "type": "boolean",
                        "required": true
                    }
                }
            }


    + Body

            {
                "_id": "53ecc8132e6e0d837bc5af70",
                "label": "bread",
                "is_done": false
            }

## Update part of the Todo [PATCH]
+ Request (application/json; charset=utf-8)

        {
          "is_done": true
        }

+ Response 204

## Update part of the Todo [PUT]
+ Request (application/json; charset=utf-8)

        {
          "label": "bread",
          "is_done": true
        }

+ Response 204

### Remove a Todo [DELETE]
+ Response 204
