FORMAT: 1A
HOST: http://localhost

# KaThinka
Is testing api for **KaThinka** project

## Retrieve Entry Point [/]
### Check if api is connected to db and running [GET]
+ Response 200 (application/json; charset=utf-8)

    + Schema

            {
                "$schema": "http://json-schema.org/draft-03/schema#",
                "type": "object",
                "required": true,
                "properties": {
                    "status": {
                        "type": "string",
                        "required": true
                    },
                    "version": {
                        "type": "string",
                        "required": true
                    }
                }
            }


# Group Users
Users related resources of the **Users API**

## Users Collection [/users]

### Create a User [POST]
+ Request (application/json; charset=utf-8)

        {
            "label": "Mario"
        }

+ Response 201 (application/json; charset=utf-8)

    + Schema

            {
                "$schema": "http://json-schema.org/draft-03/schema#",
                "type": "object",
                "required": true,
                "properties": {
                    "_id": {
                        "type": "string",
                        "required": true
                    },
                    "label": {
                        "type": "string",
                        "required": true
                    }
                }
            }

### List all Users [GET]
+ Response 200 (application/json; charset=utf-8)

    + Schema

            {
                "$schema": "http://json-schema.org/draft-03/schema#",
                "type": "array",
                "required": true,
                "items": [{
                    "type": "object",
                    "properties": {
                      "label": {
                        "type": "string",
                        "required": true
                      },
                      "_id": {
                        "type": "string",
                        "required": true
                      }
                    }
                }]
            }

## User [/users/{label}]
A single User object with all its details

+ Parameters
    + label (required, string, `Mario`) ... user label `label` of the User to perform action with.


### Retrieve a User [GET]
+ Response 200 (application/json; charset=utf-8)

    + Schema

            {
                "$schema": "http://json-schema.org/draft-03/schema#",
                "type": "object",
                "required": true,
                "properties": {
                    "_id": {
                        "type": "string",
                        "required": true
                    },
                    "label": {
                        "type": "string",
                        "required": true
                    }
                }
            }

### Remove a User [DELETE]
+ Response 204
